baseURL = "https://www.ber.gp/"
languageCode = "en-us"
title = "Paul's blog"
theme = "organic"
enableRobotsTXT = true
enableEmoji = true

[minify]
  disableSVG = true

[build]
  writeStats = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "monokai"
  tabWidth = 2

[params]
  name = "Paul Berg"
  shortBio = "Computer Science student"
  description = "I am a 22 years old computer science student interested in Machine Learning, Data-science and many more fields. You can learn more about me by looking at my projects or by downloading my resume."
  LinkedInLink = "https://www.linkedin.com/in/paul-brg"
  GithubLink = "https://github.com/Pangoraw"
